import streamlit as st

# Set the title of the web page
st.title("Welcome to Atreyu.AI")

# Introduction and Purpose
st.header("Introduction")

st.markdown("""
Atreyu.AI is a cutting-edge platform dedicated to showcasing the capabilities and advancements in conversational artificial intelligence. Our mission is to provide users with an accessible and engaging way to explore and interact with state-of-the-art AI models. Whether you're here to learn about AI, stay updated on the latest technological advancements, or experience the power of AI through our chatbot, Atreyu.AI is designed with you in mind.
""")

st.subheader("What You Can Find Here")

st.markdown("""
- **AI Chatbot**: At the heart of Atreyu.AI is our chatbot, powered by open-source models like Meta's Llama 3. This allows users to engage in natural, human-like conversations with an AI that continuously evolves and improves. Soon, we will be introducing a second chatbot featuring closed-source models from industry leaders like OpenAI and Anthropic, providing even more robust and diverse interactions.

- **Learn About AI**: Our "Learn" section offers a wealth of information tailored to beginners and enthusiasts alike. Here, you'll find clear and concise explanations of key AI and machine learning concepts, designed to help you understand the technology that powers modern AI systems.

- **Stay Informed**: The "News" section is your go-to source for the latest developments in AI and technology. We curate headlines and stories that highlight important breakthroughs, ethical considerations, and industry trends, ensuring you stay informed in a rapidly changing field.

### Our Vision

At Atreyu.AI, we believe in the potential of AI to transform the world for the better. Our platform not only aims to demonstrate the capabilities of current AI technologies but also to make these advancements accessible to a broader audience. We are committed to fostering a deeper understanding of AI, promoting ethical practices, and showcasing how AI can be leveraged safely and responsibly.

### Developer: Ron Vallejo

Thank you for visiting Atreyu.AI. We invite you to explore, learn, and engage with the future of AI.
""")

# Disclaimer
st.markdown("""
***Disclaimer***: *This application uses advanced generative AI technology to provide responses and generate content. While we strive for accuracy, the information generated by the AI may not always be correct or up-to-date. Users are strongly advised to fact-check the information and use the application at their own risk. The developers of this application are not responsible for any consequences resulting from the use of the information provided. By using this application, you acknowledge and agree to these terms.*
""")